/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UPDATE_USER;

import ADD_USER.add_user;
import BILLING.MAIN;
import LiIST.user_list;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import start.login;

/**
 *
 * @author SHREYA
 */
public class update_user extends javax.swing.JFrame {

    /**
     * Creates new form update_form
     */
    public update_user() {
        initComponents();
        upDB();
//        DATA();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtUsername_user = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtPassword_user = new javax.swing.JTextField();
        jtxtAddress_user = new javax.swing.JTextField();
        jtxtphoneno_user = new javax.swing.JTextField();
        UPDATE_ACTION = new javax.swing.JButton();
        CANCEL = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();
        USER_ID = new javax.swing.JLabel();
        ID_USER = new javax.swing.JTextField();
        AU_list = new javax.swing.JButton();
        AU_BILLING = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();
        LOGIN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Update = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 153, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("   UPDATE  USER");
        jLabel1.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Username:");

        jtxtUsername_user.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Password:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Address:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Phone No:");

        jtxtPassword_user.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        jtxtAddress_user.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        jtxtphoneno_user.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        UPDATE_ACTION.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        UPDATE_ACTION.setText("Update");
        UPDATE_ACTION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATE_ACTIONActionPerformed(evt);
            }
        });

        CANCEL.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        CANCEL.setText("RESET");
        CANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELActionPerformed(evt);
            }
        });

        EXIT.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        EXIT.setText("Exit");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });

        USER_ID.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        USER_ID.setText("USER ID:");

        ID_USER.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        AU_list.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        AU_list.setText("List");
        AU_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AU_listActionPerformed(evt);
            }
        });

        AU_BILLING.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        AU_BILLING.setText("Billing");
        AU_BILLING.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AU_BILLINGActionPerformed(evt);
            }
        });

        DELETE.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        DELETE.setText("Delete");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });

        LOGIN.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        LOGIN.setText("Login");
        LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGINActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtUsername_user, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtPassword_user, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtAddress_user, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtphoneno_user, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(AU_list, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AU_BILLING)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(USER_ID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ID_USER, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(UPDATE_ACTION, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(CANCEL)
                                .addGap(45, 45, 45)
                                .addComponent(EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(DELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtxtPassword_user, jtxtUsername_user});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jLabel4, jLabel5, jLabel6});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AU_list)
                        .addComponent(AU_BILLING))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ID_USER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(USER_ID)))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtUsername_user, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtxtPassword_user, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtAddress_user, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtphoneno_user, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UPDATE_ACTION, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CANCEL)
                    .addComponent(EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LOGIN))
                .addGap(23, 23, 23))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jtxtPassword_user, jtxtUsername_user});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jLabel4, jLabel5, jLabel6});

        jTable_Update.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "username", "password", "address", "phoneno"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_UpdateMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Update);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    Connection con1;
PreparedStatement ps; 

   public void upDB(){
          int c;
    try{
         con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=convertToNull","root","shreya22@");
           ps=con1.prepareStatement("SELECT * FROM java_billing_system.user_info");
    ResultSet re=ps.executeQuery();
    ResultSetMetaData Rss=re.getMetaData();
    c=Rss.getColumnCount();
     DefaultTableModel df=(DefaultTableModel)jTable_Update.getModel();
         df.setRowCount(0);
         while(re.next())
         {
             Vector v2=new Vector();
             for(int a=1;a<=c;a++)
             {

                 v2.add(re.getString("id"));
                 v2.add(re.getString("user_name"));
                 v2.add(re.getString("user_password"));
                 v2.add(re.getString("user_address"));
                 v2.add(re.getString("user_phoneno"));
                
             }
             
             df.addRow(v2);
         }
    }   catch(SQLException ex)
{
            java.util.logging.Logger.getLogger(update_user.class.getName()).log(Level.SEVERE, null, ex);
}
    
   }
        public String b1,b2,b3,b4,b0;
   public void Update(){
  
         try {
              int updateItem=JOptionPane.showConfirmDialog(frame, "Confirm if you want to Update","Warning",
            JOptionPane.YES_NO_OPTION);
             if(updateItem ==JOptionPane.YES_OPTION){
             b0 =ID_USER.getText();
           con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=convertToNull","root","shreya22@");
           ps=con1.prepareStatement("UPDATE java_billing_system.user_info set  user_name =?, user_password =?, user_address =?, user_phoneno =? where id=?");
           ps.setString(1,b1);
           ps.setString(2,b2);
           ps.setString(3,b3);
           ps.setString(4,b4);
           ps.setString(5, b0);
           ps.executeUpdate();
           upDB();
             }
           
       } catch (SQLException ex) {
           Logger.getLogger(update_user.class.getName()).log(Level.SEVERE, null, ex);
       }
   }
    
    
    private void UPDATE_ACTIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATE_ACTIONActionPerformed
        b1=jtxtUsername_user.getText();
        b2=jtxtPassword_user.getText();
        b3=jtxtAddress_user.getText();
        b4=jtxtphoneno_user.getText();
    Update();


    }//GEN-LAST:event_UPDATE_ACTIONActionPerformed

    private void CANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELActionPerformed

         int CancelItem=JOptionPane.showConfirmDialog(frame, "Confirm if you want to RESET","Warning",
            JOptionPane.YES_NO_OPTION);
             if(CancelItem ==JOptionPane.YES_OPTION){
        jtxtUsername_user.setText("");
        jtxtPassword_user.setText("");
        jtxtAddress_user.setText("");
        jtxtphoneno_user.setText("");
          ID_USER.setText("");
             }
    }//GEN-LAST:event_CANCELActionPerformed
private JFrame frame;
    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed

        frame =new JFrame("EXIT");
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to Exit","Billing System",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
    System.exit(0);
    }//GEN-LAST:event_EXITActionPerformed

    private void AU_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AU_listActionPerformed
        user_list a=new user_list();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AU_listActionPerformed

    private void AU_BILLINGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AU_BILLINGActionPerformed
        MAIN a=new MAIN();
        a.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_AU_BILLINGActionPerformed

    private void jTable_UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_UpdateMouseClicked
      
            //********************Selection Query****************************//

         DefaultTableModel df=(DefaultTableModel)jTable_Update.getModel();
         int selectedRowIndex=jTable_Update.getSelectedRow();
          ID_USER.setText(df.getValueAt(selectedRowIndex,0).toString());
        jtxtUsername_user.setText(df.getValueAt(selectedRowIndex,1).toString());
        jtxtPassword_user.setText(df.getValueAt(selectedRowIndex,2).toString());
        jtxtAddress_user.setText(df.getValueAt(selectedRowIndex,3).toString());
        jtxtphoneno_user.setText(df.getValueAt(selectedRowIndex,4).toString());
    }//GEN-LAST:event_jTable_UpdateMouseClicked

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
        Delete();
        
    }//GEN-LAST:event_DELETEActionPerformed

    private void LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGINActionPerformed
       login a=new login();
       this.dispose();
       a.setVisible(true);
    }//GEN-LAST:event_LOGINActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AU_BILLING;
    private javax.swing.JButton AU_list;
    private javax.swing.JButton CANCEL;
    private javax.swing.JButton DELETE;
    private javax.swing.JButton EXIT;
    private javax.swing.JTextField ID_USER;
    private javax.swing.JButton LOGIN;
    private javax.swing.JButton UPDATE_ACTION;
    private javax.swing.JLabel USER_ID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Update;
    private javax.swing.JTextField jtxtAddress_user;
    private javax.swing.JTextField jtxtPassword_user;
    private javax.swing.JTextField jtxtUsername_user;
    private javax.swing.JTextField jtxtphoneno_user;
    // End of variables declaration//GEN-END:variables

    private void Delete() {
         try {
             b0 =ID_USER.getText();
//             if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to Exit","Billing System",
//            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
             int deleteItem=JOptionPane.showConfirmDialog(frame, "Confirm if you want to Delete","Warning",
            JOptionPane.YES_NO_OPTION);
             if(deleteItem ==JOptionPane.YES_OPTION){
                 
        
           con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=convertToNull","root","shreya22@");
           ps=con1.prepareStatement("Delete from java_billing_system.user_info where id=?");
            ps.setString(1, b0);
           ps.executeUpdate();
           upDB();
                   jtxtUsername_user.setText("");
        jtxtPassword_user.setText("");
        jtxtAddress_user.setText("");
        jtxtphoneno_user.setText("");
          ID_USER.setText("");
              }
           
            
           
       } catch (SQLException ex) {
           Logger.getLogger(update_user.class.getName()).log(Level.SEVERE, null, ex);
       }
    }
    
    
    
    
}
  
      
    

